language: php

php:
  - 7.1

services:
  - mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer require satooshi/php-coveralls:dev-master squizlabs/php_codesniffer:2.* -n ; fi
  - mysql -e 'create database tink;'
  - mysql tink < db/tinktest.sql
  - mkdir cache && mkdir cache/data
  - vendor/bin/phinx migrate && vendor/bin/phinx seed:run
 
script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then mkdir -p build/logs && vendor/bin/phpunit --coverage-clover build/logs/clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then phpunit ; fi


after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then php vendor/bin/coveralls -v ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml ; fi
